name: flutter_shop
description: Flutter Shopping Cart Sample
version: 0.1.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  provider: ^3.1.0
  shared_preferences: 0.5.3+4
  english_words: ^3.1.5
  carousel_slider: ^1.3.1
  flutter_sticky_header: "^0.4.0"

  package_info: ^0.4.0+6
  url_launcher: ^5.1.4
  graphql_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/images/bottom/
      - assets/images/round/